apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
  storageClassName: ""               
